# Translations template for networking-powervm.
# Copyright (C) 2016 IBM Corp.
# This file is distributed under the same license as the networking-powervm
# project.
# Automatically generated, 2016.
#
msgid ""
msgstr ""
"Project-Id-Version: networking-powervm 1.0.0.0rc2.dev34\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2016-04-14 09:09-0400\n"
"PO-Revision-Date: 2016-04-14 09:09-0400\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.3.2\n"

#: networking_powervm/plugins/ibm/agent/powervm/agent_base.py:52
msgid ""
"The number of seconds agent will wait between polling when exception is "
"caught"
msgstr ""
"捕获到异常时，代理进程进行轮询之间将等待的"
"秒数"

#: networking_powervm/plugins/ibm/agent/powervm/agent_base.py:55
msgid ""
"The number of seconds the agent will wait between polling for local "
"device changes."
msgstr ""
"在轮询本地设备更改之间，"
"代理程序将等待的秒数。"

#: networking_powervm/plugins/ibm/agent/powervm/agent_base.py:58
msgid ""
"The number of seconds the agent should wait between heal/optimize "
"intervals.  Should be higher than the polling_interval as it runs in the "
"nearest polling loop."
msgstr ""
"在恢复/优化时间间隔之间，"
"代理程序应等待的秒数。应大于轮询时间间隔，"
"因为它在最近的轮询循环中运行。"

#: networking_powervm/plugins/ibm/agent/powervm/exceptions.py:21
#, python-format
msgid "Expected exactly one host; found %(host_count)d"
msgstr "仅期望一个主机；但是找到 %(host_count)d 个主机"

#: networking_powervm/plugins/ibm/agent/powervm/exceptions.py:25
msgid ""
"There are no network bridges (ex. Shared Ethernet Adapters) on the "
"system.  Can not start the Neutron agent."
msgstr ""
"系统上不存在网桥（例如，共享以太网适配器）。"
"无法启动 Neutron 代理进程。"

#: networking_powervm/plugins/ibm/agent/powervm/exceptions.py:30
msgid ""
"The system has more than one network bridge, but the bridge_mappings have"
" not been specified.  Please configure the bridge_mappings before "
"proceeding."
msgstr ""
"系统具有多个网桥，"
"但是尚未指定 bridge_mappings。请先配置 bridge_mappings，"
"然后再继续操作。"

#: networking_powervm/plugins/ibm/agent/powervm/exceptions.py:36
#, python-format
msgid ""
"Device %(dev)s on Virtual I/O Server %(vios)s was not found.  Unable to "
"set up physical network %(phys_net)s."
msgstr ""
"在 Virtual I/O Server %(vios)s 上找不到设备 %(dev)s。"
"无法设置物理网络 %(phys_net)s。"


# ENGL1SH_VERS10N 55289_3 DO NOT REMOVE OR CHANGE THIS LINE
# T9N_SRC_ID 52
# T9N_SH1P_STR1NG PV131AAP001 3
