# Translations template for networking-powervm.
# Copyright (C) 2016 IBM Corp.
# This file is distributed under the same license as the networking-powervm
# project.
# Automatically generated, 2016.
#
msgid ""
msgstr ""
"Project-Id-Version: networking-powervm 3.0.0.0b3\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2016-09-04 23:10-0400\n"
"PO-Revision-Date: 2016-09-04 23:10-0400\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.3.4\n"

#: networking_powervm/plugins/ibm/agent/powervm/agent_base.py:190
#, python-format
msgid "Unable to parse URI %s for provision request assessment."
msgstr "无法解析 URI %s 以进行供应请求评估。"

#: networking_powervm/plugins/ibm/agent/powervm/agent_base.py:348
#, python-format
msgid "Sending device DOWN to Neutron for %(dev)s"
msgstr "正将设备 DOWN 发送至 %(dev)s 的 Neutron"

#: networking_powervm/plugins/ibm/agent/powervm/agent_base.py:556
msgid "Error has been encountered and logged.  The agent will retry again."
msgstr "已遇到错误并记录。代理进程将再次重试。"

#: networking_powervm/plugins/ibm/agent/powervm/sea_agent.py:161
msgid "An error occurred while attempting to update the PVID of the virtual NIC."
msgstr "尝试更新虚拟 NIC 的 PVID 时发生错误。"

#: networking_powervm/plugins/ibm/agent/powervm/sea_agent.py:389
#, python-format
msgid "Cleaning up VLAN %(vlan)s from the system. It is no longer in use."
msgstr "正在从系统中清除 VLAN %(vlan)s。它已不再使用。"

#: networking_powervm/plugins/ibm/agent/powervm/sea_agent.py:402
#, python-format
msgid ""
"System identified that VLAN %(vlan)s is unused. However three VLAN clean "
"ups have already occurred in this pass. Will clean up in next "
"optimization pass."
msgstr ""
"系统已发现未使用 VLAN %(vlan)s。但是，此轮中已发生三次 VLAN 清除。"
"将在下一个优化轮中"
"清除。"

#: networking_powervm/plugins/ibm/agent/powervm/sea_agent.py:461
#, python-format
msgid ""
"Unable to determine the Network Bridge (Shared Ethernet Adapter) for "
"physical network %s.  Will be unable to determine appropriate "
"provisioning action."
msgstr ""
"无法确定物理网络"
"%s 的网桥（共享以太网适配器）。将无法确定相应的"
"供应操作。"

#: networking_powervm/plugins/ibm/agent/powervm/utils.py:142
msgid ""
"The bridge_mappings for the agent was not specified.  There was exactly "
"one Network Bridge on the system.  Agent is assuming the default network "
"is backed by the single Network Bridge."
msgstr ""
"未指定代理进程的 bridge_mappings。系统中刚好"
"有一个网桥。代理进程假定缺省网络"
"由该单个网桥支持。"

#: networking_powervm/plugins/ibm/agent/powervm/utils.py:327
msgid "No NetworkBridges detected on the host."
msgstr "主机上未检测到任何网桥。"


# ENGL1SH_VERS10N 10418_4 DO NOT REMOVE OR CHANGE THIS LINE
# T9N_SRC_ID 37
# T9N_SH1P_STR1NG PV132AAP001 1
