# Translations template for networking-powervm.
# Copyright (C) 2016 IBM Corp.
# This file is distributed under the same license as the networking-powervm
# project.
# Automatically generated, 2016.
#
msgid ""
msgstr ""
"Project-Id-Version: networking-powervm 1.0.0.0rc2.dev34\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2016-04-14 09:09-0400\n"
"PO-Revision-Date: 2016-04-14 09:09-0400\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.3.2\n"

#: networking_powervm/plugins/ibm/agent/powervm/agent_base.py:52
msgid ""
"The number of seconds agent will wait between polling when exception is "
"caught"
msgstr ""
"Время ожидания агента (в секундах) между опросами при "
"исключительной ситуации"

#: networking_powervm/plugins/ibm/agent/powervm/agent_base.py:55
msgid ""
"The number of seconds the agent will wait between polling for local "
"device changes."
msgstr ""
"Интервал опроса агентом локальных устройств на предмет наличия "
"изменений."

#: networking_powervm/plugins/ibm/agent/powervm/agent_base.py:58
msgid ""
"The number of seconds the agent should wait between heal/optimize "
"intervals.  Should be higher than the polling_interval as it runs in the "
"nearest polling loop."
msgstr ""
"Время в секундах, в течение которого агент должен ожидать между интервалами "
"исправления/оптимизации. Это значение должно быть больше значения polling_interval, так как "
"процесс выполняется в ближайшем цикле опроса."

#: networking_powervm/plugins/ibm/agent/powervm/exceptions.py:21
#, python-format
msgid "Expected exactly one host; found %(host_count)d"
msgstr "Ожидался только один хост; обнаружено: %(host_count)d"

#: networking_powervm/plugins/ibm/agent/powervm/exceptions.py:25
msgid ""
"There are no network bridges (ex. Shared Ethernet Adapters) on the "
"system.  Can not start the Neutron agent."
msgstr ""
"Нет сетевых мостов (ранее - общие адаптеры Ethernet) в "
"системе. Не удается запустить агент Neutron."

#: networking_powervm/plugins/ibm/agent/powervm/exceptions.py:30
msgid ""
"The system has more than one network bridge, but the bridge_mappings have"
" not been specified.  Please configure the bridge_mappings before "
"proceeding."
msgstr ""
"Система содержит несколько сетевых мостов, однако параметры bridge_mapping"
" не указаны. Настройте bridge_mappings перед "
"продолжением."

#: networking_powervm/plugins/ibm/agent/powervm/exceptions.py:36
#, python-format
msgid ""
"Device %(dev)s on Virtual I/O Server %(vios)s was not found.  Unable to "
"set up physical network %(phys_net)s."
msgstr ""
"Не найдено устройство %(dev)s на виртуальном сервере ввода-вывода %(vios)s. Невозможно "
"настроить физическую сеть %(phys_net)s."


# ENGL1SH_VERS10N 55289_3 DO NOT REMOVE OR CHANGE THIS LINE
# T9N_SRC_ID 52
# T9N_SH1P_STR1NG PV131AAP001 3
