# Translations template for networking-powervm.
# Copyright (C) 2016 IBM Corp.
# This file is distributed under the same license as the networking-powervm
# project.
# Automatically generated, 2016.
#
msgid ""
msgstr ""
"Project-Id-Version: networking-powervm 1.0.0.0rc2.dev34\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2016-04-14 09:09-0400\n"
"PO-Revision-Date: 2016-04-14 09:09-0400\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.3.2\n"

#: networking_powervm/plugins/ibm/agent/powervm/agent_base.py:177
#, python-format
msgid "Unable to parse URI %s for provision request assessment."
msgstr "Не удалось проанализировать URI %s для оценки запроса на выделение ресурсов."

#: networking_powervm/plugins/ibm/agent/powervm/agent_base.py:495
msgid "Error has been encountered and logged.  The agent will retry again."
msgstr "Произошла ошибка. Сведения о ней занесены в протокол. Агент повторит операцию."

#: networking_powervm/plugins/ibm/agent/powervm/sea_agent.py:158
msgid "An error occurred while attempting to update the PVID of the virtual NIC."
msgstr "При попытке обновления PVID виртуального NIC произошла ошибка."

#: networking_powervm/plugins/ibm/agent/powervm/sea_agent.py:369
#, python-format
msgid "Cleaning up VLAN %(vlan)s from the system. It is no longer in use."
msgstr "Удаление VLAN %(vlan)s из системы. Она больше не используется."

#: networking_powervm/plugins/ibm/agent/powervm/sea_agent.py:427
#, python-format
msgid ""
"Unable to determine the Network Bridge (Shared Ethernet Adapter) for "
"physical network %s.  Will be unable to determine appropriate "
"provisioning action."
msgstr ""
"Не удается определить сетевой мост (общий адаптер Ethernet) для "
"физической сети %s. В этом случае выбор правильного действия для "
"предоставления ресурсов будет невозможен."

#: networking_powervm/plugins/ibm/agent/powervm/utils.py:142
msgid ""
"The bridge_mappings for the agent was not specified.  There was exactly "
"one Network Bridge on the system.  Agent is assuming the default network "
"is backed by the single Network Bridge."
msgstr ""
"Не указано значение bridge_mappings для агента. В системе был ровно один "
"сетевой мост. Агент предполагает, что сеть по умолчанию "
"поддерживается одним сетевым мостом."

#: networking_powervm/plugins/ibm/agent/powervm/utils.py:325
msgid "No NetworkBridges detected on the host."
msgstr "На хосте не обнаружено ни одного сетевого моста."


# ENGL1SH_VERS10N 36276_3 DO NOT REMOVE OR CHANGE THIS LINE
# T9N_SRC_ID 37
# T9N_SH1P_STR1NG PV131AAP001 3
