# Translations template for networking-powervm.
# Copyright (C) 2016 IBM Corp.
# This file is distributed under the same license as the networking-powervm
# project.
# Automatically generated, 2016.
#
msgid ""
msgstr ""
"Project-Id-Version: networking-powervm 3.0.0.0rc2.dev4\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2016-10-07 02:04-0400\n"
"PO-Revision-Date: 2016-10-07 02:04-0400\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.3.4\n"

#: networking_powervm/plugins/ibm/agent/powervm/agent_base.py:190
#, python-format
msgid "Unable to parse URI %s for provision request assessment."
msgstr "Não é possível analisar o URI %s para avaliação de solicitação de provisão."

#: networking_powervm/plugins/ibm/agent/powervm/agent_base.py:348
#, python-format
msgid "Sending device DOWN to Neutron for %(dev)s"
msgstr "Enviando o dispositivo DOWN para Neutron para %(dev)s"

#: networking_powervm/plugins/ibm/agent/powervm/agent_base.py:556
msgid "Error has been encountered and logged.  The agent will retry again."
msgstr "Erro foi encontrado e registrado. O agente tentará novamente."

#: networking_powervm/plugins/ibm/agent/powervm/sea_agent.py:203
#, python-format
msgid "Cleaning up VLAN %(vlan)s from the system. It is no longer in use."
msgstr "Limpando o VLAN%(vlan)s do sistema. Ele não está mais em uso."

#: networking_powervm/plugins/ibm/agent/powervm/sea_agent.py:216
#, python-format
msgid ""
"System identified that VLAN %(vlan)s is unused. However three VLAN clean ups "
"have already occurred in this pass. Will clean up in next optimization pass."
msgstr ""
"O sistema identificou que a VLAN %(vlan)s não é usada. No entanto, três limpezas de VLAN"
"já ocorreram nessa transmissão. A limpeza ocorrerá na próxima transmissão de otimização."

#: networking_powervm/plugins/ibm/agent/powervm/sea_agent.py:273
#, python-format
msgid ""
"Unable to determine the Network Bridge (Shared Ethernet Adapter) for "
"physical network %s.  Will be unable to determine appropriate provisioning "
"action."
msgstr ""
"Não é possível determinar a ponte de rede (adaptador Ethernet compartilhado) para "
"a rede física %s.  Não será possível determinar a ação de fornecimento"
"apropriada."

#: networking_powervm/plugins/ibm/agent/powervm/sriov_agent.py:156
#, python-format
msgid "Timed out looking for vNIC with MAC %s.  Not setting device_up."
msgstr "Tempo limite atingido ao procurar vNIC com MAC %s.  Não configurar o device_up."

#: networking_powervm/plugins/ibm/agent/powervm/utils.py:142
msgid ""
"The bridge_mappings for the agent was not specified.  There was exactly one "
"Network Bridge on the system.  Agent is assuming the default network is "
"backed by the single Network Bridge."
msgstr ""
"O bridge_mappings para o agente não foi especificado.  Havia exatamente uma"
"ponte de rede no sistema.  O agente que está assumindo a rede padrão é "
"suportado pela única ponte de rede."

#: networking_powervm/plugins/ibm/agent/powervm/utils.py:327
msgid "No NetworkBridges detected on the host."
msgstr "Nenhum NetworkBridges detectado no host."

# ENGL1SH_VERS10N 43250_4 DO NOT REMOVE OR CHANGE THIS LINE
# T9N_SRC_ID 37
# T9N_SH1P_STR1NG PV132AAP001 2
