# Translations template for networking-powervm.
# Copyright (C) 2016 IBM Corp.
# This file is distributed under the same license as the networking-powervm
# project.
# Automatically generated, 2016.
#
msgid ""
msgstr ""
"Project-Id-Version: networking-powervm 3.0.0.0b3\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2016-09-04 23:10-0400\n"
"PO-Revision-Date: 2016-09-04 23:10-0400\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.3.4\n"

#: networking_powervm/plugins/ibm/agent/powervm/agent_base.py:337
msgid "Failed reporting state!"
msgstr "상태 보고 실패!"

#: networking_powervm/plugins/ibm/agent/powervm/exceptions.py:23
#, python-format
msgid "Expected exactly one host; found %(host_count)d."
msgstr "정확히 하나의 호스트를 예상했지만 %(host_count)d개를 찾았습니다."

#: networking_powervm/plugins/ibm/agent/powervm/exceptions.py:27
msgid ""
"There are no network bridges (Shared Ethernet Adapters) on the system.  "
"Can not start the Neutron agent."
msgstr ""
"시스템에 네트워크 브릿지(공유 이더넷 어댑터)가 없습니다."
"Neutron 에이전트를 시작할 수 없습니다."

#: networking_powervm/plugins/ibm/agent/powervm/exceptions.py:32
msgid ""
"The system has more than one network bridge, but the bridge_mappings have"
" not been specified.  Please configure the bridge_mappings before "
"proceeding."
msgstr ""
"시스템에 두 개 이상의 네트워크 브릿지가 있지만 bridge_mappings가 "
"지정되지 않았습니다. 진행하기 전에 bridge_mappings를 "
"구성하십시오."

#: networking_powervm/plugins/ibm/agent/powervm/exceptions.py:38
#, python-format
msgid ""
"Device %(dev)s on Virtual I/O Server %(vios)s was not found.  Unable to "
"set up physical network %(phys_net)s."
msgstr ""
"Virtual I/O Server %(vios)s의 %(dev)s 장치를 찾을 수 없습니다. "
"네트워크 %(phys_net)s을(를) 설정할 수 없습니다. "

#: networking_powervm/plugins/ibm/agent/powervm/sea_agent.py:177
#, python-format
msgid ""
"Unable to update PVID to %(pvid)s for MAC Address %(mac)s as there was no"
" valid network adapter found."
msgstr ""
"올바른 네트워크 어댑터를 찾을 수 없으므로 MAC 주소 %(mac)s에 대한 "
"PVID를 %(pvid)s(으)로 업데이트할 수 없습니다."

#: networking_powervm/plugins/ibm/agent/powervm/sea_agent.py:185
#, python-format
msgid "Existing Adapter %(num)d: mac %(mac)s, pvid %(pvid)d"
msgstr "기존 어댑터 %(num)d: MAC %(mac)s, PVID %(pvid)d"


# ENGL1SH_VERS10N 15415_3 DO NOT REMOVE OR CHANGE THIS LINE
# T9N_SRC_ID 36
# T9N_SH1P_STR1NG PV132AAP001 1
