# Translations template for networking-powervm.
# Copyright (C) 2016 IBM Corp.
# This file is distributed under the same license as the networking-powervm
# project.
# Automatically generated, 2016.
#
msgid ""
msgstr ""
"Project-Id-Version: networking-powervm 3.0.0.0rc2.dev4\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2016-10-07 02:04-0400\n"
"PO-Revision-Date: 2016-10-07 02:04-0400\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.3.4\n"

#: networking_powervm/plugins/ibm/agent/powervm/agent_base.py:190
#, python-format
msgid "Unable to parse URI %s for provision request assessment."
msgstr "URI %s für die Beurteilung der Bereitstellungsanforderung konnte nicht analysiert werden."

#: networking_powervm/plugins/ibm/agent/powervm/agent_base.py:348
#, python-format
msgid "Sending device DOWN to Neutron for %(dev)s"
msgstr "Senden von Einheit INAKTIV an Neutron für %(dev)s"

#: networking_powervm/plugins/ibm/agent/powervm/agent_base.py:556
msgid "Error has been encountered and logged.  The agent will retry again."
msgstr "Ein Fehler ist aufgetreten und wurde protokolliert. Der Agent versucht es erneut."

#: networking_powervm/plugins/ibm/agent/powervm/sea_agent.py:203
#, python-format
msgid "Cleaning up VLAN %(vlan)s from the system. It is no longer in use."
msgstr "Bereinigung von VLAN %(vlan)s aus dem System. Es wird nicht mehr verwendet."

#: networking_powervm/plugins/ibm/agent/powervm/sea_agent.py:216
#, python-format
msgid ""
"System identified that VLAN %(vlan)s is unused. However three VLAN clean ups "
"have already occurred in this pass. Will clean up in next optimization pass."
msgstr ""
"System hat angezeigt, dass VLAN %(vlan)s nicht verwendet wird. Es sind jedoch drei VLAN-Bereinigungen "
"in diesem Durchlauf erfolgt. Bereinigung erfolgt im nächsten Optimierungsdurchlauf."

#: networking_powervm/plugins/ibm/agent/powervm/sea_agent.py:273
#, python-format
msgid ""
"Unable to determine the Network Bridge (Shared Ethernet Adapter) for "
"physical network %s.  Will be unable to determine appropriate provisioning "
"action."
msgstr ""
"Die Netzbrücke (gemeinsam genutzter Ethernet-Adapter) für "
"das physische Netz %s konnte nicht bestimmt werden. Es ist nicht möglich, die entsprechende "
"Bereitstellungsaktion zu bestimmen."

#: networking_powervm/plugins/ibm/agent/powervm/sriov_agent.py:156
#, python-format
msgid "Timed out looking for vNIC with MAC %s.  Not setting device_up."
msgstr "Zeitlimitüberschreitung beim Suchen nach vNIC mit MAC %s. device_up wird nicht festgelegt."

#: networking_powervm/plugins/ibm/agent/powervm/utils.py:142
msgid ""
"The bridge_mappings for the agent was not specified.  There was exactly one "
"Network Bridge on the system.  Agent is assuming the default network is "
"backed by the single Network Bridge."
msgstr ""
"Die bridge_mappings für den Agenten wurden nicht angegeben. Es gab genau eine "
"Netzbrücke im System. Der Agent setzt voraus, dass das Standardnetz "
"durch die einzige Netzbrücke gesichert wird."

#: networking_powervm/plugins/ibm/agent/powervm/utils.py:327
msgid "No NetworkBridges detected on the host."
msgstr "Im Host wurden keine Netzbrücken erkannt."

# ENGL1SH_VERS10N 43250_4 DO NOT REMOVE OR CHANGE THIS LINE
# T9N_SRC_ID 37
# T9N_SH1P_STR1NG PV132AAP001 2
