# Translations template for networking-powervm.
# Copyright (C) 2016 IBM Corp.
# This file is distributed under the same license as the networking-powervm
# project.
# Automatically generated, 2016.
#
msgid ""
msgstr ""
"Project-Id-Version: networking-powervm 1.0.0.0rc2.dev34\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2016-04-14 09:09-0400\n"
"PO-Revision-Date: 2016-04-14 09:09-0400\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.3.2\n"

#: networking_powervm/plugins/ibm/agent/powervm/agent_base.py:52
msgid ""
"The number of seconds agent will wait between polling when exception is "
"caught"
msgstr ""
"在捕捉到異常狀況時，代理程式將在兩次輪詢之間"
"等待的秒數"

#: networking_powervm/plugins/ibm/agent/powervm/agent_base.py:55
msgid ""
"The number of seconds the agent will wait between polling for local "
"device changes."
msgstr ""
"輪詢本端裝置變更之間代理程式"
"將等待的秒數。"

#: networking_powervm/plugins/ibm/agent/powervm/agent_base.py:58
msgid ""
"The number of seconds the agent should wait between heal/optimize "
"intervals.  Should be higher than the polling_interval as it runs in the "
"nearest polling loop."
msgstr ""
"在恢復/最佳化間隔之間，代理程式應該等待的"
"秒數。應該大於 polling_interval，因為它在"
"最近的輪詢迴圈中執行。"

#: networking_powervm/plugins/ibm/agent/powervm/exceptions.py:21
#, python-format
msgid "Expected exactly one host; found %(host_count)d"
msgstr "預期只找到一個主機；但卻找到 %(host_count)d 個"

#: networking_powervm/plugins/ibm/agent/powervm/exceptions.py:25
msgid ""
"There are no network bridges (ex. Shared Ethernet Adapters) on the "
"system.  Can not start the Neutron agent."
msgstr ""
"系統上沒有網路橋接器（例如「共用乙太網路"
"配接卡」）。無法啟動 Neutron 代理程式。"

#: networking_powervm/plugins/ibm/agent/powervm/exceptions.py:30
msgid ""
"The system has more than one network bridge, but the bridge_mappings have"
" not been specified.  Please configure the bridge_mappings before "
"proceeding."
msgstr ""
"系統具有多個網路橋接器，但尚未指定"
"bridge_mappings。請先配置 bridge_mappings，然後再"
"繼續。"

#: networking_powervm/plugins/ibm/agent/powervm/exceptions.py:36
#, python-format
msgid ""
"Device %(dev)s on Virtual I/O Server %(vios)s was not found.  Unable to "
"set up physical network %(phys_net)s."
msgstr ""
"找不到 Virtual I/O Server %(vios)s 上的裝置 %(dev)s。無法"
"設定實體網路 %(phys_net)s。"


# ENGL1SH_VERS10N 55289_3 DO NOT REMOVE OR CHANGE THIS LINE
# T9N_SRC_ID 52
# T9N_SH1P_STR1NG PV131AAP001 3
