# Translations template for networking-powervm.
# Copyright (C) 2016 IBM Corp.
# This file is distributed under the same license as the networking-powervm
# project.
# Automatically generated, 2016.
#
msgid ""
msgstr ""
"Project-Id-Version: networking-powervm 3.0.0.0rc2.dev4\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2016-10-07 02:04-0400\n"
"PO-Revision-Date: 2016-10-07 02:04-0400\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.3.4\n"

#: networking_powervm/plugins/ibm/agent/powervm/agent_base.py:190
#, python-format
msgid "Unable to parse URI %s for provision request assessment."
msgstr "無法剖析 URI %s 以進行供應要求評量。"

#: networking_powervm/plugins/ibm/agent/powervm/agent_base.py:348
#, python-format
msgid "Sending device DOWN to Neutron for %(dev)s"
msgstr "正在將裝置「已關閉」傳送至適用於 %(dev)s 的 Neutron"

#: networking_powervm/plugins/ibm/agent/powervm/agent_base.py:556
msgid "Error has been encountered and logged.  The agent will retry again."
msgstr "發生錯誤並已記載。代理程式將再次重試。"

#: networking_powervm/plugins/ibm/agent/powervm/sea_agent.py:203
#, python-format
msgid "Cleaning up VLAN %(vlan)s from the system. It is no longer in use."
msgstr "正在從系統清除 VLAN %(vlan)s。將不再使用它。"

#: networking_powervm/plugins/ibm/agent/powervm/sea_agent.py:216
#, python-format
msgid ""
"System identified that VLAN %(vlan)s is unused. However three VLAN clean ups "
"have already occurred in this pass. Will clean up in next optimization pass."
msgstr ""
"系統識別到未使用 VLAN %(vlan)s。不過，在此傳遞中"
"已經發生了 3 次 VLAN 清除。將在下一次最佳化傳遞中清除。"

#: networking_powervm/plugins/ibm/agent/powervm/sea_agent.py:273
#, python-format
msgid ""
"Unable to determine the Network Bridge (Shared Ethernet Adapter) for "
"physical network %s.  Will be unable to determine appropriate provisioning "
"action."
msgstr ""
"無法判定下列實體網路的網路橋接器（共用乙太網路配接卡）："
"%s。將無法判定適當的供應"
"動作。"

#: networking_powervm/plugins/ibm/agent/powervm/sriov_agent.py:156
#, python-format
msgid "Timed out looking for vNIC with MAC %s.  Not setting device_up."
msgstr "尋找 MAC 為 %s 的 vNIC 時逾時。未設定 device_up。"

#: networking_powervm/plugins/ibm/agent/powervm/utils.py:142
msgid ""
"The bridge_mappings for the agent was not specified.  There was exactly one "
"Network Bridge on the system.  Agent is assuming the default network is "
"backed by the single Network Bridge."
msgstr ""
"未指定代理程式的 bridge_mappings。系統上只有一個"
"網路橋接器。代理程式將假定預設網路"
"由單一網路橋接器支援。"

#: networking_powervm/plugins/ibm/agent/powervm/utils.py:327
msgid "No NetworkBridges detected on the host."
msgstr "未在主機上偵測到 NetworkBridge。"

# ENGL1SH_VERS10N 43250_4 DO NOT REMOVE OR CHANGE THIS LINE
# T9N_SRC_ID 37
# T9N_SH1P_STR1NG PV132AAP001 2
