# Translations template for networking-powervm.
# Copyright (C) 2016 IBM Corp.
# This file is distributed under the same license as the networking-powervm
# project.
# Automatically generated, 2016.
#
msgid ""
msgstr ""
"Project-Id-Version: networking-powervm 1.0.0.0rc2.dev34\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2016-04-14 09:09-0400\n"
"PO-Revision-Date: 2016-04-14 09:09-0400\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.3.2\n"

#: networking_powervm/plugins/ibm/agent/powervm/agent_base.py:52
msgid ""
"The number of seconds agent will wait between polling when exception is "
"caught"
msgstr ""
"例外の検出時にポーリング間でエージェントが待機する時間 (秒)。"

#: networking_powervm/plugins/ibm/agent/powervm/agent_base.py:55
msgid ""
"The number of seconds the agent will wait between polling for local "
"device changes."
msgstr ""
"ローカル・デバイスの変更のポーリング間にエージェントが待機する"
"間隔 (秒)。"

#: networking_powervm/plugins/ibm/agent/powervm/agent_base.py:58
msgid ""
"The number of seconds the agent should wait between heal/optimize "
"intervals.  Should be higher than the polling_interval as it runs in the "
"nearest polling loop."
msgstr ""
"修復/最適化間隔でエージェントが待機しなければならない時間 (秒)。"
"エージェントは最も近いポーリング・ループで実行されるため、この値は"
"polling_interval より大きくなければなりません。"

#: networking_powervm/plugins/ibm/agent/powervm/exceptions.py:21
#, python-format
msgid "Expected exactly one host; found %(host_count)d"
msgstr "予期されたホストは 1 つのみです。検出されたのは %(host_count)d 個です"

#: networking_powervm/plugins/ibm/agent/powervm/exceptions.py:25
msgid ""
"There are no network bridges (ex. Shared Ethernet Adapters) on the "
"system.  Can not start the Neutron agent."
msgstr ""
"システム上にネットワーク・ブリッジ (共用イーサネット・アダプターなど) が"
"ありません。Neutron エージェントを開始できません。"

#: networking_powervm/plugins/ibm/agent/powervm/exceptions.py:30
msgid ""
"The system has more than one network bridge, but the bridge_mappings have"
" not been specified.  Please configure the bridge_mappings before "
"proceeding."
msgstr ""
"システムには複数のネットワーク・ブリッジが存在しますが、bridge_mapping が"
"指定されていません。先に進む前に、bridge_mapping を構成してください。"

#: networking_powervm/plugins/ibm/agent/powervm/exceptions.py:36
#, python-format
msgid ""
"Device %(dev)s on Virtual I/O Server %(vios)s was not found.  Unable to "
"set up physical network %(phys_net)s."
msgstr ""
"Virtual I/O Server %(vios)s 上にデバイス %(dev)s が見つかりませんでした。"
"物理ネットワーク %(phys_net)s をセットアップできません。"


# ENGL1SH_VERS10N 55289_3 DO NOT REMOVE OR CHANGE THIS LINE
# T9N_SRC_ID 52
# T9N_SH1P_STR1NG PV131AAP001 3
