# Translations template for networking-powervm.
# Copyright (C) 2016 IBM Corp.
# This file is distributed under the same license as the networking-powervm
# project.
# Automatically generated, 2016.
#
msgid ""
msgstr ""
"Project-Id-Version: networking-powervm 3.0.0.0b3\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2016-09-04 23:10-0400\n"
"PO-Revision-Date: 2016-09-04 23:10-0400\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.3.4\n"

#: networking_powervm/plugins/ibm/agent/powervm/agent_base.py:337
msgid "Failed reporting state!"
msgstr "状態レポートに失敗しました。"

#: networking_powervm/plugins/ibm/agent/powervm/exceptions.py:23
#, python-format
msgid "Expected exactly one host; found %(host_count)d."
msgstr "1 つのホストのみが予期されていましたが、%(host_count)d 個が見つかりました。"

#: networking_powervm/plugins/ibm/agent/powervm/exceptions.py:27
msgid ""
"There are no network bridges (Shared Ethernet Adapters) on the system.  "
"Can not start the Neutron agent."
msgstr ""
"システム上にネットワーク・ブリッジ (共用イーサネット・アダプター) がありません。"
"Neutron エージェントを開始できません。"

#: networking_powervm/plugins/ibm/agent/powervm/exceptions.py:32
msgid ""
"The system has more than one network bridge, but the bridge_mappings have"
" not been specified.  Please configure the bridge_mappings before "
"proceeding."
msgstr ""
"システムには複数のネットワーク・ブリッジが存在しますが、bridge_mapping が"
"指定されていません。先に進む前に、bridge_mapping を構成してください。"

#: networking_powervm/plugins/ibm/agent/powervm/exceptions.py:38
#, python-format
msgid ""
"Device %(dev)s on Virtual I/O Server %(vios)s was not found.  Unable to "
"set up physical network %(phys_net)s."
msgstr ""
"Virtual I/O Server %(vios)s 上にデバイス %(dev)s が見つかりませんでした。"
"物理ネットワーク %(phys_net)s をセットアップできません。"

#: networking_powervm/plugins/ibm/agent/powervm/sea_agent.py:177
#, python-format
msgid ""
"Unable to update PVID to %(pvid)s for MAC Address %(mac)s as there was no"
" valid network adapter found."
msgstr ""
"有効なネットワーク・アダプターが見つからなかったため、MAC アドレス %(mac)s の PVID を %(pvid)s に更新できません。"

#: networking_powervm/plugins/ibm/agent/powervm/sea_agent.py:185
#, python-format
msgid "Existing Adapter %(num)d: mac %(mac)s, pvid %(pvid)d"
msgstr "既存のアダプター %(num)d: mac %(mac)s、pvid %(pvid)d"


# ENGL1SH_VERS10N 15415_3 DO NOT REMOVE OR CHANGE THIS LINE
# T9N_SRC_ID 36
# T9N_SH1P_STR1NG PV132AAP001 1
